struct Vec3 {
  x: float;
  y: float;
  z: float;
}

struct Box {
  vec1: Vec3;
  vec2: Vec3;
}

struct Info {
  v1: uint16;
  v2: uint16;
}

table InstanceData {
  instanceScale:Vec3;
  instanceRot:Vec3;
  instancePos:Vec3;
}

table Instance {
  mayaPath:string;
  mayaName:string;
  b1:Box;
  b2:Box;
  data:[InstanceData];
}

table ReproMesh {
  name:string;
  matrix:Box;
  instances:[Instance];
}

table ModelInstances {
  version:Info;
  boundingBox:Box;
  repromesh:[ReproMesh];
}

root_type ModelInstances;